apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-hms
subjects:
- kind: User
  name: calico-hms
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: calico-node
  apiGroup: rbac.authorization.k8s.io