---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Calico HMS protected autoscale group into a base networking environment

Parameters:

  EnvironmentName:
    Type: String
    Description: An environment name that will be prefixed to resource names and outputs

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  ImageId:
    Description: AMI id for the instances.
    Type: AWS::EC2::Image::Id

  InstanceType:
    Description: EC2 instance type for the node instances
    Type: String

  NodeCount:
    Description: Number of instances
    Default: 1
    Type: String

Resources:

  NodeGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${AWS::StackName}-asg"
      DesiredCapacity: !Ref NodeCount
      LaunchConfigurationName: !Ref NodeLaunchConfig
      MinSize: 0
      MaxSize: 15
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${EnvironmentName}:PublicSubnet0"
        - Fn::ImportValue: !Sub "${EnvironmentName}:PublicSubnet1"
        - Fn::ImportValue: !Sub "${EnvironmentName}:PublicSubnet2"
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-node"
        PropagateAtLaunch: 'true'
      - Key: "region"
        Value: !Ref "AWS::Region"
        PropagateAtLaunch: 'true'
      - Key: "environment_type"
        Value: "aws"
        PropagateAtLaunch: 'true'
      - Key: "platform_type"
        Value: "vm"
        PropagateAtLaunch: 'true'
      - Key: !Sub "k8s-app"
        Value: 'calico-hms'
        PropagateAtLaunch: 'true'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'

  NodeLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: 'true'
      IamInstanceProfile:
        Fn::ImportValue: !Sub "${EnvironmentName}:CalicoHMSNodeInstanceProfileArn"
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - Fn::ImportValue: !Sub "${EnvironmentName}:CalicoHMSNodeSecurityGroup"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
            DeleteOnTermination: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -o xtrace
            echo "user data"
